---
- hosts: all
  tasks:
    - name: install apache2
      apt: pkg=apache2 state=latest
      become: true
    - name: execute a shell command
      shell: date 
      register: shell_result
    - debug:
      var: shell_result.stdout_linies